### ISSUE TITLE
[Feature Request] BIGGER PREVIEW TO HELP PICK

### ISSUE THREAD

**Issue by KusStar** [cyrus-cai/Gradient-Craft#1]
can hardly to pick cuz they look almost the same.

![image](https://github.com/user-attachments/assets/57525c3e-77d2-49f5-811e-3a38e841ee3f)

**Comment by cyrus-cai** [comment]
thx. I'll do some optimize.

**Comment by KusStar** [comment]
Thank you, kiss kiss😘😘

**Comment by cyrus-cai** [comment]
please try v0.1.1
https://www.gcraft.site/gradients
![Frame 5 (3)](https://github.com/user-attachments/assets/86434930-652c-4359-b3be-c96b755297eb)
